services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,qs
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENCRYPTION_KEY=your-super-secret-encryption-key
      - GENERIC_TIMEZONE=Europe/Madrid
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./volumes/n8n_data:/home/node/.n8n

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    restart: unless-stopped
    volumes:
        - ./volumes/postgres:/var/lib/postgresql/data  

  pgvector:
    image: pgvector/pgvector:pg17
    ports:
     - 5555:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./pgvector-init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./volumes/pgvector:/var/lib/postgresql/data  